fix(schemas): updated schemas and submodule for v0.4.0, minor addition to CONTRIBUTION.md code block
yazi-rs/schemas pull request #38
Opened 2024-12-08 21:32 UTC by lamteteeow

Migrating to Yazi@0.4.0 mentioned on [Issue#1772](https://github.com/sxyazi/yazi/issues/1772):
- Ran `update-submodules.sh`
- Ran `pnpm format`
- **keymap.json**: replaced `select` with `pick`, added `spot`
- **theme.json**: replaced `select` with `pick`, added `mode`, added `confirm`
> `confirm` has 2 properties that are not clear at the moment: `content` and `list` so I set them both to any type. If this could be cleared up, I could add some changes. I am assuming them to both have `{ "$ref": "#/$defs/style" }`.
- **yazi.json**:  replaced `select` with `pick`, added [PR#34](https://github.com/yazi-rs/schemas/pull/34) as well, since it fits to this PR and the [author](https://github.com/Tyarel8) seems to be inactive at the moment
- **CONTRIBUTION.md**: added a minor lang-description to the code block because of markdown linter's warning

2024-12-09 05:14 UTC, uncenter requested changes

2024-12-09 05:14 UTC, uncenter commented on schemas/yazi.json
`manager.sort_by` needs to be updated, see 2.2 of https://github.com/sxyazi/yazi/issues/1772#issue-2583804307.

2024-12-09 05:14 UTC, uncenter commented on schemas/theme.json
`flavor.use` needs to be replaced by `flavor.light` and `flavor.dark` as per 1 of https://github.com/sxyazi/yazi/issues/1772#issuecomment-2511313367.

2024-12-09 05:22 UTC, uncenter requested changes
Please read the contributing documentation: https://github.com/yazi-rs/schemas/blob/main/CONTRIBUTING.md#updating-for-a-new-yazi-release. It does not look like you have gone through the commit changes fully. I didn't go through all of the commits so far but here are the first things I noticed. Please keep going through them as instructed.

2024-12-09 05:22 UTC, uncenter commented on schemas/theme.json
The `mode_*` options of `status` were not removed and the `permissions_*` options were not renamed. See https://github.com/sxyazi/yazi/commit/5e48df5126a64c4753ce0034bc1a1667203de88b#diff-c6d275824c5b904519a6bebe03b2d43980a658fe1ddccd34e29fa48482d194e3L88.

2024-12-09 05:22 UTC, uncenter commented on schemas/yazi.json
`plugin.spotters` was not added, see https://github.com/sxyazi/yazi/commit/1f32601dc4163b419257b74777271c283a32dca6#diff-62c176c03cb77cb11e287cf9fe420fe603abd55296017d7323328e37eb056818L92.

2024-12-11 14:48 UTC, uncenter requested changes

2024-12-11 14:48 UTC, uncenter commented on schemas/yazi.json
> +				"append_spotters": { "$ref": "#/$defs/spotters" },
There is no definition for `#/$defs/spotters`. See the `$defs` object at the bottom. Should just have `name`, `mime`, and `run`, so taking from the `previewers` def:

```json
		"spotters": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": { "type": "string" },
					"mime": { "type": "string" },
					"run": { "type": "string" }
				},
				"oneOf": [
					{
						"required": ["mime", "run"]
					},
					{
						"required": ["name", "run"]
					}
				]
			}
		},
```

2024-12-11 14:48 UTC, uncenter commented on schemas/yazi.json
> +				},
create_title can still be a single string - if you look at the diff (https://github.com/sxyazi/yazi/commit/dfe2884110d24515b591192be94b17c44689015d#diff-86ad26ab85d77e4bd594a4813c46c5292a93e9ddfc9f4c224e3b9d8627635b74, `yazi-config/src/popup/input.rs`), you'll see:
```rs
pub enum InputCreateTitle {
	One(String),
	Two([String; 2]),
}
```

This should work - fix the spaces in the formatting though. Make sure to test it!
```suggestion
				"create_title": {
			        "oneOf": [
			          {
			            "type": "array",
			            "items": { "type": "string" },
			            "minItems": 2,
			            "maxItems": 2
			          },
			          {
			            "type": "string"
			          }
			        ]
				},
```

2024-12-11 14:53 UTC, uncenter commented
Eh, I'll merge and fix the rest myself so we can get this through quickly. Thanks for contributing!

2024-12-11 14:53 UTC, merged

2024-12-11 15:16 UTC, lamteteeow commented
@uncenter thanks a lot for the time and sorry for all the trouble. I'll make sure to improve myself on upcoming contributions.

2024-12-11 15:20 UTC, uncenter commented
No worries! You did great thank you.